global:
  scrape_interval: 1m
scrape_configs:
- job_name: prometheus
  scrape_interval: 1m
  static_configs:
  - targets:
    - localhost:9090
- job_name: MySliceNodeExporterTest1
  static_configs:
  - targets:
    - 10.133.130.2:9100
    - 10.130.138.2:9100
