version: '3'
    
services:
  fabric-multitool:
    image: fabrictestbed/slice-vm-rocky8-multitool:0.0.1 
    container_name: fabric
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
    volumes:
      - /home/rocky:/home/fabric/host

