version: '3'
    
services:
  frrouting:
    image: frrouting/frr 
    #image: pruth/fabric-multitool-rockylinux8:latest 
    container_name: fabric
    privileged: true
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
    volumes:
      - ./frr:/etc/frr
    network_mode: "none"

